import Navigation from '@/components/Navigation/Navigation'
import './globals.css'

export const metadata = {
  title: 'Picker Image',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
          <body>
          {/* <header><MenuBar/></header> */}
              <Navigation/>
              {children}
          </body>
      </html>
  );
}
